CREATE TABLE KHACHHANG(
	MAKH NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(500) NOT NULL,
	SDT INT NOT NULL,
	CMND INT NOT NULL
);
CREATE TABLE CHINHANH(
	MACN NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENCN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(500) NOT NULL,
	SDT INT NOT NULL
);
CREATE TABLE NHANVIEN(
	MANV NVARCHAR(20) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	TENDANGNHAP NVARCHAR(20) NOT NULL,
	MATKHAU CHAR(32) NOT NULL,
	NGSINH DATE NOT NULL,
	SOCMND INT NOT NULL,
	DIACHI NVARCHAR(500) NOT NULL,
	QUYEN INT NOT NULL,
	SDT INT NOT NULL,
	MACN NVARCHAR(20) NOT NULL,
    
    FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN)
);
CREATE TABLE SANPHAM(
    MASP NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENSP NVARCHAR NOT NULL,
	DONGIA MONEY NOT NULL,
	MACN NVARCHAR(20) NOT NULL,
	DVT NVARCHAR NOT NULL,
    
    FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN)
);
CREATE TABLE HOADONXUAT(
	SOHDXUAT NVARCHAR(20) NOT NULL PRIMARY KEY,
	MANV NVARCHAR(20) NOT NULL,
	MAKH NVARCHAR(20) NOT NULL,
	NGHD DATE NOT NULL,
    
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
 );
 CREATE TABLE CTHDXUAT(
    SOHDXUAT NVARCHAR(20) NOT NULL,
	SOLUONG INT NOT NULL,
	MASP NVARCHAR(20) NOT NULL,
	THANHTIEN MONEY,
     
    PRIMARY KEY(SOHDXUAT, MASP),
    FOREIGN KEY (SOHDXUAT) REFERENCES HOADONXUAT(SOHDXUAT),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
 );
 CREATE TABLE NHACUNGCAP(
    MANCC NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENNCC NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(500) NOT NULL,
	SDT INT NOT NULL,
	EMAIL VARCHAR NOT NULL
 );
 CREATE TABLE HOADONNHAP(
	SOHDNHAP NVARCHAR(20) NOT NULL PRIMARY KEY,
	MANV NVARCHAR(20) NOT NULL,
	MANCC NVARCHAR(20) NOT NULL,
	NGHD DATE NOT NULL,
    
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
 );
 CREATE TABLE CTHDNHAP(
    SOHDNHAP NVARCHAR(20) NOT NULL,
	SOLUONG INT NOT NULL,
	MASP NVARCHAR(20) NOT NULL,
	THANHTIEN MONEY,
     
    PRIMARY KEY(SOHDNHAP, MASP),
    FOREIGN KEY (SOHDNHAP) REFERENCES HOADONNHAP(SOHDNHAP),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
 );
 CREATE TABLE LOAIXE(
    MALOAI NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENLOAI NVARCHAR(30) NOT NULL   
 );
 CREATE TABLE XE(
    MAXE NVARCHAR(20) NOT NULL PRIMARY KEY,
	SOKHUNG NVARCHAR NOT NULL,
	KHOILUONG FLOAT NOT NULL,
	DUNGTICHBX FLOAT NOT NULL,
	LOAIDC NVARCHAR NOT NULL,
	DUNGTICHXL FLOAT NOT NULL,
	PITTONG NVARCHAR NOT NULL,
	TYSONEN CHAR(20) NOT NULL,
	CONGSUATMAX NVARCHAR NOT NULL,
	DUNGTICHNHOT NVARCHAR NOT NULL,
	TRUYENDONG NVARCHAR NOT NULL,
	HTKHOIDONG NVARCHAR NOT NULL,
	MASP NVARCHAR(20) NOT NULL,
	MALOAI NVARCHAR(20) NOT NULL,
     
    FOREIGN KEY (MALOAI) REFERENCES LOAIXE(MALOAI),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
 );
CREATE TABLE PHUTUNG(
    MAPT NVARCHAR(20) NOT NULL PRIMARY KEY,
	MOTA  NVARCHAR(20) NOT NULL,
	MASP  NVARCHAR(20) NOT NULL,
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
