CREATE TABLE CAPBAC (
    MACB char(5) NOT NULL PRIMARY KEY, 
    TENCAPBAC CHAR(20) NOT NULL
);
CREATE TABLE NHANVIEN (
    MANV CHAR(5) NOT NULL PRIMARY KEY, 
    TENDANGNHAP CHAR(12) NOT NULL, 
    MATKHAU CHAR(12) NOT NULL, 
    MACB CHAR(5) NOT NULL, 
    HOTEN CHAR(50) NOT NULL, 
    NGSINH DATE NOT NULL, 
    GIOITINH CHAR(3) NOT NULL, 
    DIACHI VARCHAR NOT NULL, 
    SDT CHAR(11) NOT NULL,
    
    FOREIGN KEY (MACB) REFERENCES CAPBAC(MACB)
);
CREATE TABLE KHACHHANG (
    MAKH CHAR(5) NOT NULL PRIMARY KEY, 
    HOTEN CHAR(50) NOT NULL, 
    NGSINH DATE NOT NULL, 
    GIOITINH CHAR(3) NOT NULL, 
    DIACHI VARCHAR NOT NULL, 
    SDT CHAR(11) NOT NULL, 
    EMAIL CHAR(50) NOT NULL, 
    GHICHU CHAR(256) NOT NULL, 
    MABAOMAT CHAR(12) NOT NULL
);
CREATE TABLE LOAISP (
    MALOAISP CHAR(5) NOT NULL PRIMARY KEY, 
    LOAISP CHAR(20) NOT NULL
);
CREATE TABLE SANPHAM (
    MASP CHAR(5) NOT NULL PRIMARY KEY,
    TENSP CHAR(30) NOT NULL, 
    GIATIEN INT NOT NULL, 
    MALOAISP CHAR(5) NOT NULL, 
    THUONGHIEU CHAR(50), 
    SOLUONG INT NOT NULL, 
    CHITIET TEXT NOT NULL,
    
    FOREIGN KEY (MALOAISP) REFERENCES LOAISP(MALOAISP)
);
CREATE TABLE SP_HINHANH (
    MASP CHAR(5) NOT NULL PRIMARY KEY, 
    HINHANH CHAR(50) NOT NULL PRIMARY KEY,
    
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
