-- sp thêm nhân viên mới
CREATE PROC sp_themNhanVien(@MANV NVARCHAR(20),
							@HOTEN NVARCHAR(50),
							@TENDANGNHAP NVARCHAR(20),
							@MATKHAU CHAR(32),
							@NGSINH DATE,
							@SOCMND INT,
							@DIACHI NVARCHAR(500),
							@QUYEN INT,
							@SDT CHAR(11) ,
							@MACN NVARCHAR(20))
AS
	IF(EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV))
	BEGIN
	PRINT N'MÃ NGƯỜI DÙNG ĐÃ TỒN TẠI'
	END
	ELSE IF(NOT EXISTS(SELECT * FROM CHINHANH WHERE MACN = @MACN))
	BEGIN
	PRINT N'KHÔNG TÌM THẤY CHI NHÁNH CÓ MÃ: '+ @MACN
	END
	ELSE
	BEGIN
	INSERT INTO NHANVIEN VALUES(@MANV, @HOTEN, @TENDANGNHAP, @MATKHAU, @NGSINH, @SOCMND, @DIACHI, @QUYEN, @SDT, @MACN)
	END
-- 
