CREATE LOGIN NhonC
WITH PASSWORD = '123456', DEFAULT_DATABASE = QLXEMAY
CREATE USER QueNhon FOR LOGIN NhonC
CREATE LOGIN LuuThanh 
WITH PASSWORD = '123456', DEFAULT_DATABASE = QLXEMAY
CREATE USER LuuThanh
CREATE LOGIN KhacManh 
WITH PASSWORD = '123456', DEFAULT_DATABASE = QLXEMAY
CREATE USER KhacManh
CREATE LOGIN VanTrong
WITH PASSWORD = '123456', DEFAULT_DATABASE = QLXEMAY
CREATE USER VanTrong
CREATE LOGIN CaoAn
WITH PASSWORD = '123456', DEFAULT_DATABASE = QLXEMAY
CREATE USER CaoAn